### ISSUE TITLE
Cannot find module 'php'

### ISSUE THREAD

**Issue by nwgat** [mkschreder/node-php#7]
nwgat@sever:~/test/node-php/tests$ nodejs express.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'php'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/nwgat/test/node-php/tests/express.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by nwgat** [comment]
change var `php = require("php");  ` to ` var php = require("../") ` in express.js fixed it for me

**Comment by likethemammal** [comment]
The `var php = require("php");` line is in the example on the npm site. Might consider changing it there too.

**Comment by bitstrider** [comment]
`var php = require("../")` doesnt work, am i missing something?

**Comment by blaskotron** [comment]
Doesn't work for me either.

**Comment by zimme** [comment]
it needs to be 'node-php' as that's the package name.
